<# ============================================================
   web-console-starter - init-app.ps1 (new project initializer)
   ------------------------------------------------------------
   Turns the template into a NEW business system in one shot:
     1. copies the template tree to the target directory
     2. writes app.config.js  (name/title/subtitle/logoText/skin)
     3. syncs names into frontend/backend package.json + index.html
     4. generates backend/.env (PORT + random JWT secret + seeds)
     5. optional: npm install + build (run with -Install)

   Usage:
     powershell -ExecutionPolicy Bypass -File init-app.ps1 `
        -AppName my-orders -Title "订单管理系统" `
        -TargetDir D:\proj\my-orders -Port 8080 -Skin light-pro -Install

   NOTE: run under Windows PowerShell 5.1+ (PS7 recommended).
   Keep AppName lowercase english/dash; values must not contain
   single quotes. Then edit backend/.env seed passwords.
   ============================================================ #>
param(
  [string]$AppName = "",          # tech id, e.g. my-orders
  [string]$Title = "",            # display title, e.g. 订单管理系统
  [string]$Subtitle = "",         # optional subtitle
  [string]$LogoText = "",         # 1-4 chars on the logo tile
  [string]$TargetDir = "",        # new system folder (absolute or relative)
  [int]$Port = 0,                 # backend port (0 = auto next free from 3000)
  [ValidateSet("deep-blue", "light-pro", "emerald-dark", "royal-purple")]
  [string]$Skin = "deep-blue",
  [switch]$Install,               # run npm install + build after copy
  [switch]$Force
)

$ErrorActionPreference = "Stop"
$templateRoot = Split-Path $PSScriptRoot -Parent

# ---------- defaults / validation ----------
if (-not $AppName) { $AppName = 'my-console' }
$AppName = ($AppName.ToLower() -replace '[^a-z0-9-]', '-').Trim('-')
if ($AppName.Length -eq 0) { throw 'AppName invalid' }
if ($Title -eq '') { $Title = $AppName }
if ($LogoText -eq '') { $LogoText = ($AppName -replace '-', '').Substring(0, [Math]::Min(4, ($AppName -replace '-', '').Length)).ToUpper() }

if (-not $TargetDir) { $TargetDir = Join-Path (Split-Path $templateRoot -Parent) $AppName }
$TargetDir = [System.IO.Path]::GetFullPath($TargetDir)

if ((Test-Path $TargetDir) -and -not $Force) {
  throw "Target exists: $TargetDir (pass -Force to overwrite)"
}
if ($Port -le 0) {
  # pick the first free port starting at 3000
  for ($p = 3000; $p -lt 9000; $p++) {
    $listening = Get-NetTCPConnection -LocalPort $p -State Listen -ErrorAction SilentlyContinue
    if (-not $listening) { $Port = $p; break }
  }
  if ($Port -le 0) { $Port = 3000 }
}

# ---------- 1. copy ----------
Write-Host "[init] 1/5 copy template -> $TargetDir"
New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
# robocopy /XD matches bare dir names or FULL paths only; use full source
# path for backend\public so a fresh project never inherits stale builds
$xd = 'node_modules', '.git', 'dist', 'logs', 'data', (Join-Path $templateRoot 'backend\public')
$xf = '*.db', 'backend.log', 'backend.pid', '.env', 'vite.config.js.timestamp-*.mjs'
$args = @($templateRoot, $TargetDir, '/E', '/XD') + $xd + @('/XF') + $xf
& robocopy @args | Out-Null
if ($LASTEXITCODE -gt 7) { throw "robocopy failed with code $LASTEXITCODE" }

# ---------- 2. app.config.js ----------
Write-Host "[init] 2/5 write app.config.js ($AppName / $Title / skin=$Skin)"
$cfg = @"
// ============================================================
// $AppName - single-point config (generated by init-app.ps1)
// ============================================================
export default {
  name: '$AppName',
  title: '$Title',
  subtitle: '$Subtitle',
  logoText: '$LogoText',

  skin: '$Skin',

  apiBase: '/api/v1',
  devPort: 5180,
  devProxyTarget: 'http://127.0.0.1:$Port',

  defaultAccountHint: 'default account: admin (see backend/.env for the seed password, change after first login)',
  skinPreview: true,
}
"@
Set-Content -Path (Join-Path $TargetDir 'app.config.js') -Value $cfg -Encoding UTF8

# ---------- 3. name sync ----------
Write-Host "[init] 3/5 sync names (package.json / index.html)"
# File.ReadAllText/WriteAllText: UTF-8 safe on PS 5.1 (Get-Content/Set-Content
# would garble CJK or add a BOM that Node's strict JSON.parse dislikes)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
foreach ($rel in @('frontend\package.json', 'backend\package.json')) {
  $p = Join-Path $TargetDir $rel
  $json = ConvertFrom-Json ([System.IO.File]::ReadAllText($p))
  $json.name = $AppName
  $json.description = "$Title (generated from web-console-starter)"
  [System.IO.File]::WriteAllText($p, ($json | ConvertTo-Json -Depth 6), $utf8NoBom)
}
$html = Join-Path $TargetDir 'frontend\index.html'
$htmlText = [System.IO.File]::ReadAllText($html) -replace '<title>[^<]*</title>', "<title>$Title</title>"
[System.IO.File]::WriteAllText($html, $htmlText, $utf8NoBom)

# ---------- 4. backend .env ----------
Write-Host "[init] 4/5 generate backend/.env (port $Port)"
$secret = ([guid]::NewGuid().ToString('N') + [guid]::NewGuid().ToString('N')).Substring(0, 48)
$envLines = @(
  '# generated by init-app.ps1 - edit before production',
  "PORT=$Port",
  'DB_PATH=./data/' + $AppName + '.db',
  "JWT_SECRET=$secret",
  'TOKEN_TTL=12h',
  'SEED_ADMIN_USER=admin',
  'SEED_ADMIN_PASS=admin123',
  'SEED_OPERATOR_USER=operator',
  'SEED_OPERATOR_PASS=op123456',
  'SEED_VIEWER_USER=viewer',
  'SEED_VIEWER_PASS=view123456'
)
Set-Content -Path (Join-Path $TargetDir 'backend\.env') -Value $envLines -Encoding UTF8

# ---------- 5. install (optional) ----------
if ($Install) {
  Write-Host "[init] 5/5 npm install + build (may take a while)..."
  Push-Location (Join-Path $TargetDir 'backend')
  npm install --no-audit --no-fund
  Pop-Location
  Push-Location (Join-Path $TargetDir 'frontend')
  npm install --no-audit --no-fund
  npm run build
  Pop-Location
} else {
  Write-Host "[init] 5/5 skipped install (pass -Install to build now)"
}

Write-Host ""
Write-Host "[init] done. New system at: $TargetDir"
Write-Host "  next:"
Write-Host "   1. cd $TargetDir\scripts && start.bat      (start on :$Port)"
Write-Host "   2. edit backend\.env  - change the seed passwords"
Write-Host "   3. check-names.ps1    - verify name sync"
Write-Host "   4. build your pages: follow AI-GUIDE.md (5 page templates)"
# robocopy leaves $LASTEXITCODE=1 on a successful copy; force a clean exit 0
exit 0
